name: Deploy to Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application
        run: |
          set -e
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 root@194.37.80.72 << 'EOF'
            set -e

            echo "Starting deployment process..."

            # Перейти в директорию приложения
            cd /root/blog || { echo 'Failed to change directory'; exit 1; }

            # Обновить код с GitHub
            echo "Pulling latest code..."
            git pull origin master || { echo 'git pull failed'; exit 1; }

            # Установить зависимости
            echo "Installing dependencies..."
            npm install || { echo 'npm install failed'; exit 1; }

            # Собрать приложение
            echo "Building the application..."
            npm run build || { echo 'build failed'; exit 1; }

            # Очистить папку prod
            echo "Cleaning prod directory..."
            rm -rf /root/blog/prod/* || { echo 'Failed to clean prod directory'; exit 1; }

            # Скопировать содержимое dist в prod
            echo "Copying dist to prod directory..."
            cp -r /root/blog/dist/* /root/blog/prod/ || { echo 'Failed to copy dist to prod'; exit 1; }

            # Остановить старую версию приложения
            echo "Stopping old processes..."
            pm2 stop all || true

            # Запустить приложение с помощью PM2
            echo "Starting the application with PM2..."
            pm2 start ~/ecosystem.config.js --env production --update-env || { echo 'PM2 start failed'; exit 1; }

            # Проверить статус процессов PM2
            echo "Checking PM2 process status..."
            sleep 5  # Задержка, чтобы дать процессам время на старт
            pm2 status || { echo 'PM2 processes are not running'; exit 1; }

            # Проверить работоспособность приложения
            echo "Checking application health..."
            curl -s -o /dev/null -w "%{http_code}" https://waves-and-mountains.blog/ | grep -q "200" && echo 'Application is running' || { echo 'Application is not running'; exit 1; }

            # Сохранить процесс PM2 (автозапуск)
            echo "Saving PM2 state..."
            pm2 save || { echo 'PM2 save failed'; exit 1; }

            echo "Deployment successful!"
          EOF
